### PR TITLE
[issue #261] Run media scanner on all exported files

### PR DESCRIPTION
**Pull request by mvglasow**
Tested successfully.

### CODE REVIEW

**Comment by nguillaumin** [comment]
Thanks, sounds good, but I was thinking this might be best if done at the end of  `FileSystemUtils.copyFile()`? This way if files are copied from elsewhere in the code they'll get automatically scanned (without having to repeat the scan code), and that'll save us the mumbo jumbo with the lists and arrays. What do you think?

**Comment by mvglasow** [comment]
Well, as I mentioned before, triggering the scan in `copyFile()` would result in one call per file – rather than one call with a list of files. Triggering all scans with one call at least gives Android the chance to do some optimization (if not in the current version, then maybe in a future one).

The argument for triggering the scan in `copyFile()` would be if that function gets called from multiple parts of the code. Is there anything else besides export that uses `copyFile()`?

**Comment by nguillaumin** [comment]
I don't think anything else uses `copyFile()` for now, but it's more about the future. I can anticipate that if somebody uses `copyFile()` to implement something else, we'll have the exact same bug because calling the media scanner will probably have been missed... And then when that happens it's likely we'll move the media scanner call in `copyFile()` anyway rather than duplicate it on the caller side?

I tend to favor maintainability over performance in this case because I don't have much time to spend on this app. unfortunately.

**Comment by mvglasow** [comment]
OK, that's a valid argument. I'll change that and file another merge request.

**Comment by nguillaumin** [comment]
Cheers.

**Pull request closed without merging**
